export const CONSTANTS = {
  HOLD_BUFFER_HOURS: 6,
  DEFAULT_MARKUP_MULTIPLIER: 2.5,
  DEFAULT_SHIPPING_BUFFER_USD: 3.0,
  DEFAULT_PAGE_LIMIT: 50,
  MAX_RETRY_ATTEMPTS: 5,
  RETRY_BACKOFF_MINUTES: 15,
  SUPPORTED_SUPPLIERS: ['CJ', 'ZENDROP'] as const,
  ORDER_STATUSES: {
    PENDING_HOLD: 'PENDING_HOLD',
    HOLD_EXPIRED: 'HOLD_EXPIRED',
    PROCESSING: 'PROCESSING',
    DISPATCHED_TO_SUPPLIER: 'DISPATCHED_TO_SUPPLIER',
    FAILED_BILLING: 'FAILED_BILLING',
    SUPPLIER_PROCESSING: 'SUPPLIER_PROCESSING',
    SHIPPED: 'SHIPPED',
    DELIVERED: 'DELIVERED',
    CANCELLED: 'CANCELLED',
    REFUNDED: 'REFUNDED',
    MANUAL_REVIEW: 'MANUAL_REVIEW',
  } as const,
  SUPPLIER_PRIORITY: {
    PRIMARY: 1,
    BACKUP: 2,
  } as const,
} as const;

export type OrderStatus = (typeof CONSTANTS.ORDER_STATUSES)[keyof typeof CONSTANTS.ORDER_STATUSES];
export type SupplierType = (typeof CONSTANTS.SUPPORTED_SUPPLIERS)[number];
