export const ORDER_STATUS_CONFIG: Record<
  string,
  { label: string; color: string; bg: string; border: string }
> = {
  PENDING_HOLD: {
    label: 'Pending Hold (6h)',
    color: 'text-amber-800',
    bg: 'bg-amber-50',
    border: 'border-amber-300',
  },
  HOLD_EXPIRED: {
    label: 'Hold Expired',
    color: 'text-orange-800',
    bg: 'bg-orange-50',
    border: 'border-orange-300',
  },
  PROCESSING: {
    label: 'Processing',
    color: 'text-blue-800',
    bg: 'bg-blue-50',
    border: 'border-blue-300',
  },
  DISPATCHED_TO_SUPPLIER: {
    label: 'Dispatched to Factory',
    color: 'text-purple-800',
    bg: 'bg-purple-50',
    border: 'border-purple-300',
  },
  FAILED_BILLING: {
    label: 'Failed Billing',
    color: 'text-rose-800',
    bg: 'bg-rose-50',
    border: 'border-rose-300',
  },
  SUPPLIER_PROCESSING: {
    label: 'Supplier Manufacturing',
    color: 'text-indigo-800',
    bg: 'bg-indigo-50',
    border: 'border-indigo-300',
  },
  SHIPPED: {
    label: 'Shipped (Tracking Active)',
    color: 'text-teal-800',
    bg: 'bg-teal-50',
    border: 'border-teal-300',
  },
  DELIVERED: {
    label: 'Delivered',
    color: 'text-emerald-800',
    bg: 'bg-emerald-50',
    border: 'border-emerald-300',
  },
  CANCELLED: {
    label: 'Cancelled',
    color: 'text-slate-700',
    bg: 'bg-slate-100',
    border: 'border-slate-300',
  },
  MANUAL_REVIEW: {
    label: 'Manual Review Required',
    color: 'text-yellow-800',
    bg: 'bg-yellow-50',
    border: 'border-yellow-300',
  },
};

export const US_STATES = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'DC', name: 'District of Columbia' },
];

export const DEFAULT_PAGE_LIMIT = 20;
export const HOLD_BUFFER_HOURS = 6;
